### PR TITLE
Python3 port

### PR DESCRIPTION
**Pull request by granquet**

### CODE REVIEW

**Review by rezib — COMMENTED** [review]
Is there any good reason to not fully drop Python 2 support? We now have Python 3 on all platforms.

If no, I would prefer to restrict support to Python 3 only for these reasons:
* Maintaining and testing Neos with Python 2 comes with a cost
* We could avoid additional external dependency on community library six
* Code (esp. singleton/metaclass) would more future proof, w/ less legacy and technical debt

**Comment by granquet** [comment]
> Is there any good reason to not fully drop Python 2 support? We now have Python 3 on all platforms.
> 
> If no, I would prefer to restrict support to Python 3 only for these reasons:
> 
>     * Maintaining and testing Neos with Python 2 comes with a cost
> 
>     * We could avoid additional external dependency on community library six
> 
>     * Code (esp. singleton/metaclass) would more future proof, w/ less legacy and technical debt

Agreed with that, it was just a bad assumption on my part.
But I'll ask to merge it anyway with python2 support as removing six and rewriting metaclass support would require a new round of validation (as it's not a cosmetic change) and I would prefer going rather quick on this one as some users are waiting eagerly for the release.
Python2 support removal can be done on the next release?

Thx,
Guillaume.

**Review by rezib — CHANGES_REQUESTED** [review]
OK for this strategy but please add six in `install_requires` of `setup.py`, unless you're very confident you can remove Python 2 support very promptly after the merge.

**Comment by granquet** [comment]
> OK for this strategy but please add six in `install_requires` of `setup.py`, unless you're very confident you can remove Python 2 support very promptly after the merge.

I've added six as a dependency (because that's the right thing to do) and I'm quite confident that somewhere next week I can produce a patch to remove python2 support. (six library removal and change of shebangs).
users are expecting a release today or tomorrow actually...

**Review by rezib — APPROVED** [review]
LGTM :+1:  Thanks for your work!

**Pull request merged**
